#!/bin/bash
# Orchestra Project Initializer
# Usage: ./init-project.sh <project-name> <src-path> <dst-remote>
#
# Example:
#   ./init-project.sh pytenet ../TeneT.jl git@github.com:you/pytenet.git

set -e

PROJECT_NAME=${1:?Usage: $0 <project-name> <src-path> <dst-remote>}
SRC_PATH=${2:?Usage: $0 <project-name> <src-path> <dst-remote>}
DST_REMOTE=${3:?Usage: $0 <project-name> <src-path> <dst-remote>}

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ORCHESTRA_DIR="$(dirname "$SCRIPT_DIR")"

echo "=== Orchestra Project Initializer ==="
echo "Project:    $PROJECT_NAME"
echo "Source:     $SRC_PATH"
echo "Remote:     $DST_REMOTE"
echo ""

# Check src exists
if [ ! -d "$SRC_PATH" ]; then
    echo "ERROR: Source path does not exist: $SRC_PATH"
    exit 1
fi

# Create project directory (sibling to orchestra)
PROJECT_DIR="$(dirname "$ORCHESTRA_DIR")/$PROJECT_NAME"

if [ -d "$PROJECT_DIR" ]; then
    echo "ERROR: Project directory already exists: $PROJECT_DIR"
    exit 1
fi

echo "Creating project at: $PROJECT_DIR"
mkdir -p "$PROJECT_DIR"
cd "$PROJECT_DIR"

# Initialize git
git init

# Copy orchestra files
cp "$ORCHESTRA_DIR/CLAUDE.md" .
cp "$ORCHESTRA_DIR/VERIFICATION_LEVELS.md" .
cp "$ORCHESTRA_DIR/EQUIVALENCE_TYPES.md" .
cp "$ORCHESTRA_DIR/TRANSLATION_ORDER.md" .
cp "$ORCHESTRA_DIR/ATOMIC_COMMIT.md" .

# Create directory structure
mkdir -p notes
mkdir -p tests/ground_truth
mkdir -p docs

# Calculate relative path to src
SRC_REL=$(python3 -c "import os.path; print(os.path.relpath('$SRC_PATH', '$PROJECT_DIR'))")

# Create orchestra.yaml
cat > orchestra.yaml << EOF
# Orchestra Declaration
# Generated by init-project.sh

src: $SRC_REL
dst: ./$PROJECT_NAME
framework: julia -> pytorch

notes: |
  # TODO: Add your domain knowledge here
  #
  # Key things to document:
  # - Index conventions (1-based vs 0-based)
  # - Memory layout differences
  # - Gradient conventions
  # - Physical constraints (energy bounds, normalization, etc.)
  # - Priority order for translation
  # - Known gotchas
EOF

# Create empty knowledge base
cat > notes/knowledge_base.md << 'EOF'
# Project Knowledge Base

This document contains ALL human decisions and domain knowledge.
**Agents: consult this before asking humans again.**

---

## Conventions

(Add decisions here as they are made)

---

## Domain Constraints

(Add physical/mathematical constraints here)

---

## Translation Decisions

(Add implementation choices here)

---

## Gotchas

(Add pitfalls and warnings here)
EOF

# Create .gitignore
cat > .gitignore << 'EOF'
__pycache__/
*.pyc
*.egg-info/
dist/
build/
.pytest_cache/
.venv/
*.npz
EOF

# Initial commit
git add -A
git commit -m "init: Orchestra translation project for $PROJECT_NAME"

# Set remote and push
git remote add origin "$DST_REMOTE"
echo ""
echo "Remote set to: $DST_REMOTE"
echo ""
echo "=== Setup Complete ==="
echo ""
echo "Next steps:"
echo "  1. cd $PROJECT_DIR"
echo "  2. Edit orchestra.yaml - add your notes"
echo "  3. Edit notes/knowledge_base.md - add domain knowledge"
echo "  4. git push -u origin main"
echo "  5. claude"
echo "  6. Say: 'Read orchestra.yaml and start translation'"
echo ""
